version: '3'

services:
  web:
    build:
      context: ./..
      dockerfile: ./docker/Dockerfile
    volumes:
      - ../src/:/app
    ports:
      - 8001:8000
    env_file:
      - ../env/.env.dev # Do not declare environment if you want this to work
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=game

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres_data: